spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eesy?serverTimezone=GMT%2B8
    username: root
    password: 1997322ld
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service # ”¶”√√˚≥∆
mybatis:
  type-aliases-package: com.study.demo.pojo
